name: Run Jest Tests for Food Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or another Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Run food tests only
      run: npx jest tests/food.test.js --coverage=false
